### ISSUE TITLE
build for mobile error

### ISSUE THREAD

**Issue by SvenWangChina** [Akryum/meteor-vite#14]
build for mobile get follow error

```
⚡️ Building packages to make them available to export analyzer...
=> Errors while initializing project:         
                                              
While loading plugin `vite` from package `vite:bundler`:
packages/vite/build.js:375:2: Command failed with exit code 1: meteor build ./.dist --directory
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Supply the server hostname and port in the --server option for mobile app
builds.


Changes to your project's package version selections:

minifier-css           removed from your project
minifier-js            removed from your project
standard-minifier-css  removed from your project
standard-minifier-js   removed from your project

at makeError (packages/vite/build.js:375:2)
at execaSync (packages/vite/build.js:375:2)
at packages/vite/build.js:235:3
at module (packages/vite/build.js:375:2)
at fileEvaluate (packages/modules-runtime.js:336:7)
at Module.require (packages/modules-runtime.js:238:14)
at require (packages/modules-runtime.js:258:21)
at packages/vite/build.js:375:2
at packages/vite/build.js:375:2
```

**Comment by Akryum** [comment]
> Supply the server hostname and port in the --server option for mobile app
builds.

This is not a vite error?
