### ISSUE TITLE
build error with aldeed:collection2

### ISSUE THREAD

**Issue by SvenWangChina** [Akryum/meteor-vite#15]
I use aldeed:collection2 for collections. I got the follow error when build app:

```
Errors prevented bundling:                    
While minifying app code:                     
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: node_modules/simpl-schema/dist/esm/validation/typeValidator/index.js  (2:0)
Line content: import { SimpleSchema } from '../../SimpleSchema.js';

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: node_modules/mongo-object/dist/index.js  (2:0)
Line content: import MongoObject from './mongo-object.js';

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)
```

**Comment by yuniit** [comment]
Hi, @SvenWangChina Are you able to fix the issue?

**Comment by yuniit** [comment]
I've got this error too while building with mup
```js
⚡️ Build successful (34911.77ms)
Errors prevented bundling:                 
While minifying app code:                  
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Export" statement may only appear at the top level)
Source file: node_modules/ky/index.js  (417:0)
Line content: export default createInstance();

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Export" statement may only appear at the top level)
Source file: node_modules/ky/index.js  (417:0)
Line content: export default createInstance();

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


```
