### ISSUE TITLE
i18n not working after switching to vite

### ISSUE THREAD

**Issue by juliandierker** [Akryum/meteor-vite#19]
Hey I maintain a big meteor typescript project and we are desperately looking for a faster bundling solution than meteor standart bundle system. We are trying out vite right now with this package and running into an issue that after installing and configurating our i18n translation in app breaks somehow.

![image](https://user-images.githubusercontent.com/18357175/212565203-3716247e-e406-4c6f-84bc-cd5f04845e7d.png)

We use i18n via `universe:i18n` and translation lives in root directory in a folder called `i18n` in yml format.

**Comment by Akryum** [comment]
Do you mind putting up a repro I can clone? Thanks!

**Comment by PatrickKaim** [comment]
Just to make sure the build is working I created a clean project and just did a build.
Build went ok but bundling didn't.

`meteor create project --vue`
And did a run => works
And a build (meteor build ../output) => errors

 meteor build ../output
⚡️ Building packages to make them available to export analyzer...
⚡️ Packages built (11591.01ms)
⚡️ Building with Vite...
vite v3.2.5 building for production...
transforming...
✓ 33 modules transformed.
rendering chunks...
node_modules/.vite-meteor/dist/meteor-entry.js   0.02 KiB / gzip: 0.04 KiB
node_modules/.vite-meteor/dist/About.js          0.59 KiB / gzip: 0.33 KiB
node_modules/.vite-meteor/dist/main.js           284.71 KiB / gzip: 67.26 KiB

⚡️ Build successful (733.51ms)
Errors prevented bundling:                    
While minifying app code:                     
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: client/main.js  (2:0)
Line content: import "./vite/meteor-entry.js"

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: client/main.js  (2:0)
Line content: import "./vite/meteor-entry.js"

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)

**Comment by PatrickKaim** [comment]
Just a follow up:
I've replaced the plugin 'vite-plugin-vue-i18n' with 'unplugin-vue-i18n' and changed the vite.config.js file a bit:
**from**:
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import {dirname, resolve} from "node:path";
import {fileURLToPath, URL} from "node:url";
import vueI18n from '@intlify/vite-plugin-vue-i18n'

export default defineConfig({
    plugins: [
        vue(),
        vueI18n({
            /!* options *!/
            // locale messages resource pre-compile option
            include: resolve(dirname(fileURLToPath(import.meta.url)), './locales/!**'),
        }),
    ],
    meteor: {
        clientEntry: 'ui/main.js',
    },
    optimizeDeps: {
        exclude: ['vue-meteor-tracker'],
    },
})
```
**to**:
```
import { fileURLToPath, URL } from "node:url";
import { resolve, dirname } from "node:path";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import VueI18nPlugin from "@intlify/unplugin-vue-i18n/vite";

export default defineConfig({
    plugins: [
        vue(),
        VueI18nPlugin({
            include: resolve(dirname(fileURLToPath(import.meta.url)), 'locales/**'),
        })
    ],
    meteor: {
        clientEntry: 'ui/main.js',
    },
    optimizeDeps: {
        exclude: ['vue-meteor-tracker'],
    }
});
```
Now the build finishes without error, so that's progress. But now the minifier errors out:
```
⚡️ Building packages to make them available to export analyzer...
⚡️ Packages built (6281.99ms)
⚡️ Building with Vite...
vite v3.2.5 building for production...
transforming...
✓ 41 modules transformed.
rendering chunks...
node_modules/.vite-meteor/dist/meteor-entry.js   0.02 KiB / gzip: 0.04 KiB
node_modules/.vite-meteor/dist/About.js          0.59 KiB / gzip: 0.33 KiB
node_modules/.vite-meteor/dist/style.css         0.34 KiB / gzip: 0.18 KiB
node_modules/.vite-meteor/dist/main.js           374.19 KiB / gzip: 86.46 KiB

⚡️ Build successful (1216.97ms)
Errors prevented bundling:                    
While minifying app code:                     
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: client/main.js  (2:0)
Line content: import "./vite/meteor-entry.js"

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: client/main.js  (2:0)
Line content: import "./vite/meteor-entry.js"

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)
```
What does this mean? Or what's is going wrong here and why? I don't understand it.
