### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by alisnic** [Akryum/meteor-vite#47]
```
1:21:33 PM [vite] Internal server error: Cannot read property 'split' of undefined
      at Context.load (file:///Users/andreilisnic/Work/<redacted>/.meteor/local/build/programs/server/assets/packages/vite_bundler/worker-dev.mjs:102:44)
      at async Object.load (file:///Users/andreilisnic/Work/<redacted>/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44323:32)
      at async loadAndTransform (file:///Users/andreilisnic/Work/p<redacted>/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:54954:24)
      at async viteTransformMiddleware (file:///Users/andreilisnic/Work/<redacted>/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64430:32)
```

My deps:

```
    "vite": "^4.5.3",
    "@vitejs/plugin-react": "^3.1.0",
```

**Comment by JorgenVatle** [comment]
Which version of the Vite bundler package are you using? Currently, the most up-to-date version is still found in the fork.

Make sure you're running the latest versions of [`meteor-vite`](https://www.npmjs.com/package/meteor-vite) and [`jorgenvatle:vite-bundler`](https://atmospherejs.com/jorgenvatle/vite-bundler).

**Comment by alisnic** [comment]
Yes, I figured that out. Thanks
